version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=zenei_db
      - POSTGRES_USER=zenei_user
      - POSTGRES_PASSWORD=zenei_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zenei-auth:
    image: ghcr.io/cloudeko/services/native/zenei:9daebd4
    restart: always
    depends_on:
      - db
    volumes:
      - ./dev/dev-private-key.pem:/key/dev-private-key.pem
      - ./dev/dev-public-key.pem:/key/dev-public-key.pem
    ports:
      - 8080:8080
    environment:
      - quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/zenei_db
      - quarkus.datasource.username=zenei_user
      - quarkus.datasource.password=zenei_password
      - smallrye.jwt.sign.key.location=/key/dev-private-key.pem
      - mp.jwt.verify.publickey.location=/key/dev-public-key.pem
      - mp.jwt.verify.issuer=https://example.com/issuer
      - quarkus.mailer.mock=true

volumes:
  postgres_data:
